name: Python package ManyLinux2010

on: push
#  push:
#    branches:
#      - 'release/aicspylibczi'

jobs:
  wheel-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine
      - name: Build manylinux Python wheels
        uses: RalfG/python-wheels-manylinux-build@v0.2.2-manylinux2010_x86_64
        with:
          python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38'
          build-requirements: 'cython'
          system-packages: 'cmake'
          package-path: ''
          pip-wheel-args: '--no-deps'
      - name: Publish wheels to PyPI
        env:
          TWINE_USERNAME: aicspypi
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          twine upload wheelhouse/*-manylinux*.whl
